import Head from 'next/head';
import React, { useMemo } from 'react';
import { tableFromIPC } from 'apache-arrow';
import { readParquet } from 'parquet-wasm';
import { useQuery } from '@tanstack/react-query';
import Map from 'react-map-gl';
import DeckGL from '@deck.gl/react/typed';
import { H3HexagonLayer } from '@deck.gl/geo-layers/typed';

import { COLORS, MAPBOX_TOKEN } from '@/constants';

import styles from '@/styles/Home.module.css';

import type { H3Row } from '@/types';

const fetchData = async () =>
  fetch('/data/fs_hex_4.parquet')
    .then(async (res) => new Uint8Array(await res.arrayBuffer()))
    .then((data) => readParquet(data));

export default function Home() {
  const fetchParquet = useQuery(['parquet'], fetchData, {
    refetchOnMount: false,
    refetchOnWindowFocus: false,
    refetchOnReconnect: false,
  });

  const { data, isLoading, isFetched, error } = fetchParquet;

  const layers = useMemo(() => {
    if (data) {
      const arrowTable = tableFromIPC(data);
      const h3Data: H3Row[] = JSON.parse(arrowTable.toString());

      const layer = new H3HexagonLayer({
        id: 'h3-hexagon-layer',
        data: h3Data,
        pickable: false,
        wireframe: false,
        filled: true,
        extruded: false,
        highPrecision: 'auto',
        elevationScale: 20,
        getHexagon: (d) => d.h3index,
        getFillColor: (d) => COLORS[d.value],
      });

      return [layer];
    }

    return [];
  }, [data]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <DeckGL
          initialViewState={{
            longitude: 0,
            latitude: 0,
            zoom: 2,
          }}
          controller={true}
          layers={layers}
        >
          <Map mapboxAccessToken={MAPBOX_TOKEN} mapStyle="mapbox://styles/mapbox/light-v10" />
        </DeckGL>
      </main>
    </>
  );
}
